PortA:
  device: color-sensor
  qos: reliable
  enable_lights: False

PortB:
  device: ultrasonic-sensor
  qos: reliable
  enable_lights: False

hub:
  hub_program_cycle: 100
  enable_imu: False
  enable_battery_management: False
  enable_button: True
  enable_speaker: False
  opening: False
